version: "3.9"

services:
  web:
    build:
      context: ./sci_book
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - static:/code/static
    depends_on:
      - sci_book_db

  sci_book_db:
    image: postgres:13
    container_name: sci_book_db_c  # исправлено с "сontainer_name" на "container_name"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - sci_book_db-data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  sci_book_db-data:
  static: